import type { Metadata } from "next";
import {  Roboto} from "next/font/google";
import "./globals.css";
// import SidebarMenu from "@/components/general UI/Sidebar";
import Footer from "@/components/general UI/Footer";
import SideMenu from "@/components/general UI/SideMenu";
import AnnouncementBar from "@/components/general UI/AnnouncementBar";

const robotoFont = Roboto({
  variable: "--font-roboto",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tulip Pictures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoFont.variable}  min-h-screen antialiased`}
      >
        <div className="flex ">
          <SideMenu />
          <div className="flex-1">
            <AnnouncementBar />
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
